### PR TITLE
Adds test phase using html-proofer

### PR DESCRIPTION
**Pull request by cloudify**

### CODE REVIEW

**Comment by cloudify** [comment]
Site has some issues currently, than needs to be fixed:

```
- ./_site/assets/toolkit/index.html
  *  internal script {{ '/build/IWT.min.js' | path }} does not exist (line 64)
  *  internal script {{ '/build/vendor/jquery.min.js' | path }} does not exist (line 40)
  *  internal script {{ '/build/vendor/modernizr.js' | path }} does not exist (line 36)
  *  internally linking to {{ '/build/build.css' | path }}, which does not exist (line 38)
     <link media="all" rel="stylesheet" href="%7B%7B%20'/build/build.css'%20%7C%20path%20%7D%7D">
- ./_site/daf/index.html
  *  662:66: ERROR: htmlParseEntityRef: expecting ';' (line 662)
htmlproofer 3.7.2 | Error:  HTML-Proofer found 5 failures!
```

**Comment by cloudify** [comment]
`./_site/assets/toolkit/index.html` looks like an unprocessed Jekyll template

**Comment by gvarisco** [comment]
Thanks for the heads up, @cloudify. I'm preparing a PR that's gonna remove the html files within the toolkit folder as they aren't needed.

**Comment by gvarisco** [comment]
Removed unneeded HTML files in 97b0b7861b91f278d6805be02a36a84842bb184a

**Comment by cloudify** [comment]
@gvarisco one last issue:

```
- ./_site/daf/index.html
  *  662:66: ERROR: htmlParseEntityRef: expecting ';' (line 662)
htmlproofer 3.7.2 | Error:  HTML-Proofer found 1 failure!
```

**Comment by gvarisco** [comment]
@cloudify saw it, fixed in 87589dc6049b18ec93f5b0f6cabd3f26b7c59ba2

**Comment by cloudify** [comment]
Issue is that there's an `&` in an `href`:

```
<a href="/assets/pdf/cap_9-Data_&_Analytics_Framework.pdf" class="u-textWeight-600 u-linkClean u-color-teal-70 u-block" target="_blank">
```

and gets parsed as an HTML entity, the `&` [must be escaped](https://stackoverflow.com/questions/3705591/do-i-encode-ampersands-in-a-href/3705601#3705601).

**Pull request merged**
